apiVersion: v1
kind: Service
metadata:
  name: lab3-db
  labels:
    app: db
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lab3-stateful
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "lab3-db"
  replicas: 2
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
