apiVersion: v1
kind: Service
metadata:
  name: lab8-clusterip
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab8-nodeport
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: lab8-lb
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - port: 80
