apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab9-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: lab9-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: lab9-pvc
